# Generated
general {
    col.active_border = rgba(eac58c77)
    col.inactive_border = rgba(d1726455)
}
misc { background_color = rgba(181d2eFF) }
plugin {
    hyprbars {
        bar_color = rgba(181d2eFF)
        col.text = rgba(dce0eeFF)
    }
}
